"""GitHubReleaseProvider — materialize published releases as synthetic git commits.

The tool doesn't parse or diff snapshots directly — it converts each release
into a single commit in a synthetic git repo, then feeds that repo to the same
extract pipeline that git-file sources use. This preserves the diff-scoped
parsing optimization (git's blob-level diff tells us which stanzas changed;
we only fastobo-parse those) and every render/query feature at zero
architectural cost.

Provenance mapping from a release to its commit:

* ``author_name`` = release publisher's login
* ``author_email`` = ``<login>@users.noreply.github.com``
* ``committed_date`` = release ``published_at``
* ``message`` = tag + release body + ``Release URL: <html_url>`` trailer
* ``sha`` = generated by git during commit (deterministic given input)
* git tag on the commit = release tag name

The ``Release URL:`` trailer in the message body is later parsed by
``extract._commit_row`` into the ``snapshot_url`` parquet column; renderers
show it as a ``→ <URL>`` line under the commit header.

Talks to GitHub through ``gh``: the CLI is already how the user authenticates
for other repo work, so it handles tokens, rate limits (5000/hour), and
retries for us. No auth/token surface to invent.
"""

import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from rich.console import Console

from ..config import GitHubReleaseSource
from ._synthetic_git import (
    commit_or_tag_head,
    git_init,
    list_local_tags,
    run_git,
)


_GITHUB_HTTPS = re.compile(r"^https?://github\.com/([^/]+/[^/]+?)(?:\.git)?/?$")


def _owner_name(repo_url: str) -> str:
    m = _GITHUB_HTTPS.match(repo_url)
    if not m:
        raise ValueError(
            f"github-release provider requires an https://github.com URL, "
            f"got {repo_url!r}"
        )
    return m.group(1)


class GitHubReleaseProvider:
    """Fetch releases from GitHub and materialize them into a git repo."""

    def __init__(self, console: Console) -> None:
        self.console = console

    def ensure_synced(
        self, source: GitHubReleaseSource, *, since: str | None = None
    ) -> str:
        """Materialize every unseen non-draft release into a synthetic commit,
        oldest first, tagged with the release name. Idempotent on re-run —
        only new releases produce new commits.

        ``since`` is accepted for interface compatibility with GitFileProvider
        but ignored here; incremental sync always happens by comparing local
        tags to remote releases.
        """
        clone_dir = source.clone_dir
        owner_name = _owner_name(source.repo)

        if not clone_dir.exists():
            clone_dir.parent.mkdir(parents=True, exist_ok=True)
            self.console.print(
                f"Initializing synthetic clone at [cyan]{clone_dir}[/] "
                f"for release-backed source [cyan]{source.name}[/] …"
            )
            git_init(clone_dir)
            local_tags: set[str] = set()
        else:
            self.console.print(
                f"Reusing clone at [cyan]{clone_dir}[/]."
            )
            local_tags = list_local_tags(clone_dir)

        self.console.print(
            f"Fetching release list from [cyan]{owner_name}[/] …"
        )
        remote_releases = self._list_remote_releases(owner_name)

        # Skip drafts, prereleases, anything already committed, and anything
        # without the configured asset. Then sort oldest-first so the git
        # history reads chronologically.
        new_releases = [
            r for r in remote_releases
            if not r.get("draft") and not r.get("prerelease")
            and r["tag_name"] not in local_tags
            and self._find_asset(r, source.asset) is not None
        ]
        new_releases.sort(key=lambda r: r["published_at"])

        if not new_releases:
            self.console.print(
                f"[dim]No new releases to materialize for {source.name}.[/]"
            )
            return str(clone_dir)

        self.console.print(
            f"Materializing [bold]{len(new_releases)}[/] release(s) …"
        )
        for release in new_releases:
            self._materialize_release(source, owner_name, release, clone_dir)

        return str(clone_dir)

    # ------------------------------------------------------------------
    # gh / git wrappers
    # ------------------------------------------------------------------

    def _list_remote_releases(self, owner_name: str) -> list[dict]:
        """Return every release in ``owner_name`` as a list of dicts."""
        # `gh api --paginate` concatenates array-shaped page responses into
        # one big JSON array, which is what we want here.
        result = subprocess.run(
            [
                "gh", "api",
                f"repos/{owner_name}/releases?per_page=100",
                "--paginate",
            ],
            capture_output=True, text=True, check=True, env=_gh_env(),
        )
        return json.loads(result.stdout)

    def _find_asset(self, release: dict, asset_name: str) -> dict | None:
        """Return the release asset object whose ``name`` == ``asset_name``,
        or ``None`` if no such asset exists on this release."""
        for asset in release.get("assets", []):
            if asset.get("name") == asset_name:
                return asset
        return None

    def _download_asset(
        self, owner_name: str, tag: str, asset_name: str, dest_dir: Path
    ) -> Path:
        """Download ``asset_name`` from release ``tag`` into ``dest_dir``.
        Returns the local path to the downloaded file."""
        subprocess.run(
            [
                "gh", "release", "download", tag,
                "--repo", owner_name,
                "--pattern", asset_name,
                "--dir", str(dest_dir),
            ],
            check=True, env=_gh_env(), capture_output=True,
        )
        return dest_dir / asset_name

    def _materialize_release(
        self,
        source: GitHubReleaseSource,
        owner_name: str,
        release: dict,
        clone_dir: Path,
    ) -> None:
        tag = release["tag_name"]
        self.console.print(
            f"  [dim]· fetching[/] [cyan]{tag}[/]"
        )
        with tempfile.TemporaryDirectory() as tmp:
            downloaded = self._download_asset(owner_name, tag, source.asset, Path(tmp))
            # Place the asset at a stable path in the clone — same filename
            # every release — so `git log --follow <asset>` walks the history
            # cleanly.
            dest = clone_dir / source.asset
            shutil.copy(downloaded, dest)

        run_git(clone_dir, "add", source.asset)
        commit_or_tag_head(
            clone_dir,
            tag,
            author_name=_release_author_name(release),
            author_email=_release_author_email(release),
            committed_date=release["published_at"],
            message=_commit_message_for(release),
            console=self.console,
        )


def _release_author_name(release: dict) -> str:
    author = release.get("author") or {}
    return str(author.get("login") or "unknown")


def _release_author_email(release: dict) -> str:
    login = _release_author_name(release)
    return f"{login}@users.noreply.github.com"


def _commit_message_for(release: dict) -> str:
    """Compose a commit message from the release. Layout:

        <tag>

        <release body, if any>

        Release URL: <html_url>

    The ``Release URL:`` trailer is later parsed by ``extract._commit_row``
    into the ``snapshot_url`` parquet column.
    """
    tag = release["tag_name"]
    body = (release.get("body") or "").strip()
    url = release.get("html_url", "")
    parts = [tag]
    if body:
        parts.append(body)
    if url:
        parts.append(f"Release URL: {url}")
    return "\n\n".join(parts)


def _gh_env() -> dict:
    """PATH + tokens gh needs, minus the update-check chatter that would
    otherwise leak into our output."""
    env = dict(os.environ)
    env["GH_NO_UPDATE_NOTIFIER"] = "1"
    return env
